### ISSUE TITLE
1.0 roadmap

### ISSUE THREAD

**Issue by take-five** [salemove/ex_freddy#3]
- [ ] Add [metrics](https://github.com/benoitc/erlang-metrics) backend support
- [ ] Add ability to create pool of consumers to RPC client
- [ ] Add unit tests
- [ ] Add documentation
